Package["Anyonica`"]

PackageExport["ListToNumberField"]

ListToNumberField::usage = 
    "ListToNumberField[l] Converts a list of numbers belonging to a finite "<>
    "extension of the rational numbers to AlgebraicNumber "<>
    "objects belonging to a common field."

Options[ListToNumberField] = 
    { 
        "MaxLength" -> 5
    };


ListToNumberField[ lis_List, opts:OptionsPattern[] ] := 
    With[ { 
            ml  = OptionValue["MaxLength"], 
            l   = Length @ lis, 
            ltn = ListToNumberField,
            tn  = ToNumberField[#,All]&
        },
        If[ 
            l <= ml, 
            tn @ lis,
            tn @ 
            Join[
                ltn @ lis[[ ;; Floor[ l / 2  ] ]],
                ltn @ lis[[ Floor[ l / 2  ] + 1 ;; ]]
            ]
        ]
    ];

PackageExport["ToCyclotomicField"]

ToCyclotomicField::usage = 
    "ToCyclotomicField[ l ] converts a list l " <>
    "of numbers to a common cyclotomic field with " <> 
    "an order smaller than the optionvalue of \"MaxOrder\", " <> 
    "if it exists and returns $Failed otherwise. Note: this function "<>
    "almost always returns warnings, this is normal since we try number "<>
    "fields one by one until one works. Using Quiet will result in bugs!";

Options[ToCyclotomicField] = 
    { 
        "MinDegree" -> 2,
        "MaxDegree" -> 528,
        "Verbose"   -> False
    };

ToCyclotomicField[ vals_, opts:OptionsPattern[] ] :=
	Module[{ result, uniquevals, newuniquevals, maxd, zetan, i, map },
        verbose    = OptionValue["Verbose"];
        i          = OptionValue["MinDegree"];
        maxd       = OptionValue["MaxDegree"];
		result     = $Failed;
        uniquevals = Union @ vals;
        map        = If[ verbose, PMap, Map ];

		While[ i < maxd,
            zetan  = ToNumberField[ Exp[ 2 Pi I / i ] ];
            If[ 
                verbose, 
                PrintTemporary["Trying to express values in cyclotomic field of degree ", i, " generated by ", zetan ] 
            ];
			result = 
                FailOnMessage[ 
                    map[ ToNumberField[ #, zetan ]&, uniquevals ], 
                    $Failed
                ];
			If[ result =!= $Failed, i = maxd ];
			i++;
		];

        If[ result === $Failed, Return @ $Failed ];

        vals /. Dispatch @ Thread[ uniquevals -> result ]

	];